; FUD firmware (Find Unwelcome Devices) - M5Stack StickS3 + Pingequa RF Pack S3
; Single target, one hardware combo.

[env:sticks3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = /dev/cu.usbmodem31101
monitor_port = /dev/cu.usbmodem31101
monitor_speed = 115200
board_build.flash_size = 8MB
board_build.arduino.memory_type = qio_opi
extra_scripts = pre:scripts/gen_images.py
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
lib_deps =
  m5stack/M5Unified
  h2zero/NimBLE-Arduino @ ^2.2.0
  crankyoldgit/IRremoteESP8266 @ ^2.8.6
