# Embeds images/*.png into a C header as raw PNG byte arrays. Faces live in
# flash, drawn with M5GFX drawPng. No SD, no runtime files. RGB565 pre-convert
# was tried and reverted (worse color, no aspect-ratio gain). Images are the
# source of truth; the generated header is disposable and gitignored.
# Runs standalone and as a PlatformIO pre-script.

import os, glob

try:
    BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
except NameError:
    BASE = os.getcwd()  # PlatformIO pre-script (SCons): cwd is the project dir

IMG_DIR = os.path.join(BASE, "images")
OUT_DIR = os.path.join(BASE, "src", "generated")
OUT = os.path.join(OUT_DIR, "image_assets.h")

def sanitize(name):
    return "".join(c if c.isalnum() else "_" for c in name)

def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    files = sorted(glob.glob(os.path.join(IMG_DIR, "*.png")))
    lines = ["// AUTO-GENERATED by scripts/gen_images.py. Do not edit.",
             "#pragma once", "#include <stdint.h>", ""]
    index = []
    for f in files:
        stem = os.path.splitext(os.path.basename(f))[0]
        sym = "img_" + sanitize(stem)
        data = open(f, "rb").read()
        lines.append("static const uint8_t %s[] = {" % sym)
        row = []
        for b in data:
            row.append("0x%02x," % b)
            if len(row) == 16:
                lines.append("  " + "".join(row)); row = []
        if row:
            lines.append("  " + "".join(row))
        lines.append("};")
        lines.append("static const uint32_t %s_len = %d;" % (sym, len(data)))
        lines.append("")
        index.append((stem, sym))
    lines.append("struct ImageAsset { const char* name; const uint8_t* data; uint32_t len; };")
    lines.append("static const ImageAsset IMAGES[] = {")
    for stem, sym in index:
        lines.append('  { "%s", %s, %s_len },' % (stem, sym, sym))
    lines.append("};")
    lines.append("static const int IMAGE_COUNT = %d;" % len(index))
    lines.append("")
    open(OUT, "w").write("\n".join(lines))
    print("gen_images: embedded %d PNGs into %s" % (len(index), OUT))

main()
